services:
  web:
    build: .
    container_name: hackathon_backend
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    expose:
      - 8000
    # ports:
    #   - "8000:8000"
    labels:
      - traefik.enable=true
      - traefik.http.routers.backend-app.rule=Host(`hackathon.flink.com.bd`)
      - traefik.http.routers.backend-app.entrypoints=web
      - traefik.http.services.backend-app.loadbalancer.server.port=8000

networks:
  dokploy-network:
    external: true
