# Generated by Django 5.2 on 2025-05-07 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_resume"),
        ("course", "0002_lesson"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="Skill",
            field=models.ManyToManyField(
                blank=True, related_name="users_with_skills", to="course.course"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="completed_course",
            field=models.ManyToManyField(
                blank=True, related_name="completed_users", to="course.course"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="verified_skills",
            field=models.ManyToManyField(
                blank=True, related_name="verified_users", to="course.skill"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
