# Generated by Django 5.2 on 2025-05-07 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0003_userprofile_skill_userprofile_completed_course_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("seeker", "Seeker"),
                    ("employer", "Employer"),
                    ("admin", "Admin"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
