# Generated by Django 5.2 on 2025-05-07 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_alter_user_user_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="Skill",
            new_name="skill",
        ),
    ]
